apiVersion: v1
kind: Service
metadata:
  labels:
    app: golarn
  name: golarn
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: golarn
  sessionAffinity: None
  type: ClusterIP
